theme = "darcula"

[editor]
rulers = [80, 120]
#cursorline = true
bufferline = "multiple"
line-number = "relative"
color-modes = true
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.lsp]
display-inlay-hints = true

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "hint"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"A-j" = ["search_selection", "extend_search_next"]
"A-h" = [":toggle lsp.display-inlay-hints"]
