theme = "darcula"

[editor]
rulers = [80, 120]
#cursorline = true
bufferline = "multiple"
line-number = "relative"
color-modes = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.lsp]
display-inlay-hints = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"A-j" = ["search_selection", "extend_search_next"]
