[[language]]
name = "rust"
indent = {tab-width = 4, unit = "\t"}

[[language]]
name = "typescript"
indent = {tab-width = 4, unit = "\t"}

[[language]]
name = "javascript"
indent = {tab-width = 4, unit = "\t"}

[[language]]
name = "json"
indent = {tab-width = 4, unit = "\t"}

[language-server.vscode-html-language-server.config]
# find formatting options at: https://github.com/beautify-web/js-beautify
format = {indentInnerHtml = true, extraLiners = "", endWithNewline = true}
provideFormatter = true

[[language]]
name = "html"
indent = {tab-width = 4, unit = "\t"}

[[language]]
name = "svelte"
indent = {tab-width = 4, unit = "\t"}

[[language]]
name = "css"
indent = {tab-width = 4, unit = "\t"}
formatter = {command = "js-beautify", args = [
	"--type",
	"css",
	"--editorconfig",
	"--space-around-selector-separator",
]}

[[language]]
name = "bash"
indent = {tab-width = 4, unit = "\t"}

[language-server.sql-language-server]
# https://github.com/joe-re/sql-language-server
command = "sql-language-server"
args = ["up", "--method", "stdio"]

[[language]]
name = "sql"
indent = {tab-width = 4, unit = "\t"}
language-servers = ["sql-language-server"]

[[language]]
name = "nix"
indent = {tab-width = 4, unit = "\t"}

[[language]]
name = "fish"
indent = {tab-width = 4, unit = "\t"}
# fish_indent does not use tabs, so we fix it that way
formatter = {command = "dash", args = ["-c", "fish_indent | sed 's/    /\t/g'"]}

[[language]]
name = "toml"
auto-format = true
formatter = {command = "taplo", args = [
	"fmt",
	"--option",
	"indent_string=\t",
	"--option",
	"compact_inline_tables=true",
	"-",
]}
